// <auto-generated />
using System;
using CachingDemo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CachingDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CachingDemo.Domain.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 473, DateTimeKind.Utc).AddTicks(77),
                            Description = "Information Technology",
                            Name = "IT",
                            UpdatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 473, DateTimeKind.Utc).AddTicks(84)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 473, DateTimeKind.Utc).AddTicks(1866),
                            Description = "Human Resources",
                            Name = "HR",
                            UpdatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 473, DateTimeKind.Utc).AddTicks(1867)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 473, DateTimeKind.Utc).AddTicks(1871),
                            Description = "Sales Department",
                            Name = "Sales",
                            UpdatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 473, DateTimeKind.Utc).AddTicks(1872)
                        });
                });

            modelBuilder.Entity("CachingDemo.Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 474, DateTimeKind.Utc).AddTicks(917),
                            DepartmentId = 1,
                            Email = "john.doe@company.com",
                            FirstName = "John",
                            HireDate = new DateTime(2026, 3, 11, 5, 54, 3, 474, DateTimeKind.Utc).AddTicks(916),
                            LastName = "Doe",
                            PhoneNumber = "123-456-7890",
                            Salary = 50000m,
                            UpdatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 474, DateTimeKind.Utc).AddTicks(918)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 474, DateTimeKind.Utc).AddTicks(3411),
                            DepartmentId = 1,
                            Email = "jane.smith@company.com",
                            FirstName = "Jane",
                            HireDate = new DateTime(2026, 3, 11, 5, 54, 3, 474, DateTimeKind.Utc).AddTicks(3411),
                            LastName = "Smith",
                            PhoneNumber = "123-456-7891",
                            Salary = 60000m,
                            UpdatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 474, DateTimeKind.Utc).AddTicks(3412)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 474, DateTimeKind.Utc).AddTicks(3416),
                            DepartmentId = 2,
                            Email = "mike.johnson@company.com",
                            FirstName = "Mike",
                            HireDate = new DateTime(2026, 3, 11, 5, 54, 3, 474, DateTimeKind.Utc).AddTicks(3416),
                            LastName = "Johnson",
                            PhoneNumber = "123-456-7892",
                            Salary = 55000m,
                            UpdatedAt = new DateTime(2026, 3, 11, 5, 54, 3, 474, DateTimeKind.Utc).AddTicks(3417)
                        });
                });

            modelBuilder.Entity("CachingDemo.Domain.Models.Employee", b =>
                {
                    b.HasOne("CachingDemo.Domain.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CachingDemo.Domain.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
